app/Nomenclature/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import ProductView, CategoryView

urlpatterns = [
    path('', cache_page(60)(ProductView.as_view()), name="home"),
    path('category/<int:pk>/', cache_page(60)(CategoryView.as_view()), name="category")
]

app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('Nomenclature.urls'))
]

app/Nomenclature/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=8, unique=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    STATUS_CODE = [
        ('in_stock', 'In stock'),
        ('out_of_stock', 'Out of stock')
    ]

    name = models.CharField(max_length=8, unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    status = models.CharField(max_length=50, choices=STATUS_CODE)
    remains = models.PositiveIntegerField()

    def __str__(self):
        return self.name

app/Nomenclature/views.py
import time

from django.views.generic import ListView

from .models import Product


class ProductView(ListView):
    model = Product
    template_name = 'index.html'
    paginate_by = 50

    def get_queryset(self):
        time.sleep(2)
        return Product.objects.all().order_by('pk')


class CategoryView(ProductView):
    def get_queryset(self):
        time.sleep(2)
        return Product.objects.filter(category_id=self.kwargs['pk']).order_by('pk')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TestProfBIT</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <div class="container">
    {% include 'include/_header.html' %}

    {% block body %}{% endblock %}


    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

app/templates/include/_header.html
  <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
    <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
      <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg>
      <span class="fs-4">Test ProfBIT</span>
    </a>
  </header>

app/templates/include/_pagination.html
<nav aria-label="Page navigation example">
  <ul class="pagination">
    {% for p in page_obj.paginator.page_range %}
    <li class="page-item">
        <a class="page-link" href="?page={{ p }}">{{ p }}</a>
    </li>
    {% endfor %}
  </ul>
</nav>

app/templates/index.html
{% extends 'base.html' %}
{% load nomenclature_tags %}
{% load cache %}

{% block body %}
<div class="row">
    <div class="col-3">
         <div class="list-group">
        {% get_categories as categories%}
        {% for category in categories %}
            <a href="{% url 'category' category.pk %}" class="list-group-item list-group-item-action">{{ category.name }}</a>
        {% endfor %}
    </div>

    </div>

    <div class="col-9">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Name</th>
              <th scope="col">Category</th>
              <th scope="col">Price</th>
              <th scope="col">Status</th>
              <th scope="col">Remains</th>
            </tr>
          </thead>
          <tbody>
            {% for product in product_list %}
            <tr>
              <td>{{ product.name }}</td>
              <td>{{ product.category }}</td>
              <td>{{ product.price }}</td>
              <td>{{ product.status }}</td>
              <td>{{ product.remains }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
    {% include 'include/_pagination.html' %}
    </div>

</div>
{% endblock %}